export const photos = [
  {
    id: 1,
    src: "/images/img1.jpg",
    link: "",
    height: "70",
    heading: "View",
    column: 1,
  },
  {
    id: 2,
    src: "/images/img4.jpg",
    link: "",
    height: "100",
    heading: "View",
    column: 1,
  },
  {
    id: 3,
    src: "/images/img5.jpg",
    link: "",
    height: "130",
    heading: "View",
    column: 1,
  },
  {
    id: 4,
    src: "/images/img6.jpg",
    link: "",
    height: "70",
    heading: "View",
    column: 2,
  },
  {
    id: 5,
    src: "/images/img7.avif",
    link: "",
    height: "100",
    heading: "View",
    column: 2,
  },
  {
    id: 6,
    src: "/images/img8.jpg",
    link: "",
    height: "130",
    heading: "View",
    column: 2,
  },
  {
    id: 7,
    src: "/images/img2.jpg",
    link: "",
    height: "130",
    heading: "View",
    column: 3,
  },
  {
    id: 8,
    src: "/images/img3.jpg",
    link: "",
    height: "100",
    heading: "View",
    column: 3,
  },
  {
    id: 9,
    src: "/images/img9.jpg",
    link: "",
    height: "130",
    heading: "View",
    column: 3,
  },
 
];
