import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NavBar from "./_components/navBar/page";
import { Toaster } from 'sonner'


const figtree = Figtree({
  variable: "--font-figtree-sans",
  subsets:["latin"],
  weight:["300","400","500"]

})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${figtree.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
           <div className="dark:bg-dark overflow-hidden">
           <NavBar />
           {children}
           </div>
          </ThemeProvider>
          <Toaster richColors  />

      </body>
    </html>
  );
}
